"""empty message

Revision ID: ca1117b43f6b
Revises: 
Create Date: 2019-05-14 18:27:39.081015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1117b43f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_alias', sa.String(length=128), nullable=True),
    sa.Column('cube', sa.LargeBinary(), nullable=True),
    sa.Column('extends', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubes_name'), 'cubes', ['name'], unique=True)
    op.create_index(op.f('ix_cubes_name_alias'), 'cubes', ['name_alias'], unique=True)
    op.create_table('dataset',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('cube_uuid', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_cube_uuid'), 'dataset', ['cube_uuid'], unique=True)
    op.create_index(op.f('ix_dataset_name'), 'dataset', ['name'], unique=True)
    op.create_table('datasource',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('config', sa.String(length=4096), nullable=True),
    sa.Column('test_sql', sa.String(length=512), nullable=True),
    sa.Column('modi_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_name'), 'datasource', ['name'], unique=True)
    op.create_index(op.f('ix_datasource_type'), 'datasource', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_type'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_name'), table_name='datasource')
    op.drop_table('datasource')
    op.drop_index(op.f('ix_dataset_name'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_cube_uuid'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_cubes_name_alias'), table_name='cubes')
    op.drop_index(op.f('ix_cubes_name'), table_name='cubes')
    op.drop_table('cubes')
    # ### end Alembic commands ###
